global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertador9@gmail.com'
  smtp_auth_username: 'alertador9@gmail.com'
  smtp_auth_password: 'jagngrpphpvesfvt'
  smtp_require_tls: true

# Enrutamiento de alertas
route:
  group_by: ['alertname', 'instance', 'name']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-admin-sys'

receivers:
  - name: 'email-admin-sys'
    email_configs:
      - to: 'ryrt32@gmail.com'
        send_resolved: false
        headers:
          subject: '============== [{{ .Status | toUpper }}] Alerta de Infraestructura: {{ .CommonLabels.alertname }} =============='
